### ISSUE TITLE
Add tests with known output

### ISSUE THREAD

**Issue by krlmlr** [hadley/pkgdown#118]
Test packages that test individual aspects of the code, and known output.

**Comment by hadley** [comment]
We could also consider running `build_site(site_page = "docs/")` as part of the tests. That would be a good start on a regression suite, and would eliminate the deployment code in travis.

**Comment by hadley** [comment]
Closing for now, I'm testing informally in quite a few places. Will start to build in more formal tests too, as pkgdown gets more complex.
