### ISSUE TITLE
Include template tailored for use with jekyll

### ISSUE THREAD

**Issue by hadley** [hadley/pkgdown#129]
Can copy from https://github.com/rstudio/shiny-dev-center/tree/master/_staticdocs (with permission from RStudio)

**Comment by jacintoArias** [comment]
In reference to jekyll templates I have created a [fork project](https://github.com/jacintoArias/jekylldocs) in which the site is generated as a set of jekyll's collections and data files.

The user can then integrate this documents in an existing jekyll website by updating its pages and templates. I've replicated (some details still missing) the original staticdocs format using this project on the [fork's website](http://jarias.es/jekylldocs/index.html).

I do not know it this comes closer to your idea on using jekyll templates, but if you feel that this could be a good addition I could work on a PR (there are almost no changes to the core code).

**Comment by hadley** [comment]
I think this is no longer necessary as part of core pkgdown, as it's now possible get templates and assets from another package.

@jacintoArias maybe you could create that package? 😄
