### ISSUE TITLE
Better default navbar

### ISSUE THREAD

**Issue by hadley** [hadley/pkgdown#158]
Should include:
- Move articles before reference
- Link to "overview" if `vignettes/packagename.Rmd` exists
- Don't show articles, if only vignette is the overview
- Automatic generation of news section, based on `vignettes/releases`

**Comment by krlmlr** [comment]
I'd like the navbar to be fixed always; currently it's fixed only for vignettes, but not e.g. for NEWS. (The rendering looks different, too -- no highlighting of NEWS sections.)
