### ISSUE TITLE
Clarify connections between aliases and topic

### ISSUE THREAD

**Issue by bborgesr** [hadley/pkgdown#160]
With the old `staticdocs`, you would have something like:

<img width="686" alt="screen shot 2016-10-03 at 8 49 45 pm" src="https://cloud.githubusercontent.com/assets/6527540/19051465/0c57357c-89ab-11e6-915b-1f85380834ca.png">

Now you have this (which really doesn't look very good in cases like these):

<img width="681" alt="screen shot 2016-10-03 at 4 09 05 pm" src="https://cloud.githubusercontent.com/assets/6527540/19051536/4552fbb8-89ab-11e6-9f03-9d78bb01721e.png">

Any way to mitigate this problem would be appreciated!

**Comment by hadley** [comment]
Currently, I'm outputting:

```html
<dl>
  <dt><a href="read_sas.html">read_sas</a></dt>
  <dt><a href="read_sas.html">write_sas</a></dt>
  <dd>Read and write SAS files.</dd>

  <dt><a href="read_spss.html">read_por</a></dt>
  <dt><a href="read_spss.html">read_sav</a></dt>
  <dt><a href="read_spss.html">read_spss</a></dt>
  <dt><a href="read_spss.html">write_sav</a></dt>
  <dd>Read SPSS (SAV &amp; POR) files. Write SAV files.</dd>
</dl>
```

But the plan is to switch to this structure:

```html
<div class="topics">
  <div class="topic">
    <ul>
      <li><a href="read_sas.html">read_sas</a></li>
      <li><a href="read_sas.html">write_sas</a></li>
    </ul>
    <p>Read and write SAS files.</p>
  </div>

  <div class="topic">
    <ul>
      <li><a href="read_spss.html">read_por</a></li>
      <li><a href="read_spss.html">read_sav</a></li>
      <li><a href="read_spss.html">read_spss</a></li>
      <li><a href="read_spss.html">write_sav</a></li>
    </ul>
    <p>Read SPSS (SAV &amp; POR) files. Write SAV files.</p>
  </div>
</div>
```

That should make it easier to style.

**Comment by hadley** [comment]
This isn't exactly what I originally proposed, but Robby suggested it and I really like it: http://hadley.github.io/pkgdown/reference/index.html.  For shiny, you might want to tweak the styles so that the lists are rendered inline.
