### ISSUE TITLE
Make it possible to skip article building

### ISSUE THREAD

**Issue by jranke** [hadley/pkgdown#168]
I have some vignettes that I would prefer not to rebuild with each pkgdown::build_site() as this takes a lot of time.

**Comment by hadley** [comment]
In that case, why not just run`build_reference()` or whatever you're currently working on?

**Comment by jranke** [comment]
Thanks for the hint - I'll give it a go!

**Comment by hadley** [comment]
If that doesn't help, I'd be open to exploring how to make caching work naturally

**Comment by jranke** [comment]
I guess you are not thinking of Makefiles ;)

**Comment by hadley** [comment]
I was thinking knitr caching
