### ISSUE TITLE
SEO'd title tags

### ISSUE THREAD

**Issue by MarkEdmondson1234** [hadley/pkgdown#171]
If the title tags are tweaked a bit in the templates, then the websites built with it will be easier found in Google for their functions and articles.  At the moment the homepage has for example `<title>Home. pkgdown</title>`which is sub-optimal. 

I suggest the following formats for the `<title>` tag:

* index.html - `packageName - packageTitle (from DESCRIPTION)`
* articles/vignettes - `articleName - packageName`
* functions - `functionName - functionDescription - packageName`

**Comment by hadley** [comment]
Why is `-` better than `.`?

**Comment by MarkEdmondson1234** [comment]
The `.` or `-` doesn't really matter (some use `|` as a sperator), its more the text in the title tag.

For example, for http://hadley.github.io/pkgdown/ its currently `<title>Home. pkgdown</title>`, where as it will get better SEO traffic with `<title>pkgdown - Make Static HTML Documentation for a Package</title>`

At the very least it will help the website created stand out above all the R package scraper websites out there, and as I didn't know the name of the package had changed may have helped me find it with a Google for "R package that writes documentation"

**Comment by hadley** [comment]
Oh I see what you mean now. Shouldn't be too hard.
