### ISSUE TITLE
vignette images not loading

### ISSUE THREAD

**Issue by goldingn** [hadley/pkgdown#172]
This is so useful, I can't believe I've only just seen it!

One hiccup; the images in our vignettes don't load, e.g.: http://goldingn.github.io/zoon/articles/Building_a_module.html

That's because the file paths in the html generated by `pkgdown::build_site()` are absolute: https://github.com/goldingn/zoon/blob/gh-pages/reference/articles/Building_a_module.html#L187

I'm guessing this is because `build_articles()` calls `rmarkdown::html_document()` with the argument `self_contained = FALSE`: https://github.com/hadley/pkgdown/blob/master/R/build-articles.R#L96, although it's not clear to me why they get the full filepath  rather than relative to wherever `build_site()` is executed.

**Comment by hadley** [comment]
Exactly how are you calling `build_site()`?

**Comment by goldingn** [comment]
I've tried in RStudio, command line R (OSX), via `Rscript` on the unix (OSX) command line and via an overly complicated [Travis hack](https://github.com/goldingn/zoon/blob/master/.deploy_pkgdown.sh#L14) ([results](https://travis-ci.org/goldingn/zoon/jobs/166327487#L1013)). I've tried running `pkgdown::build_site()` on all of these and `library(pkgdown); build_site()` on a couple.

In all cases, the top level of [this repo](https://github.com/goldingn/zoon) is the working directory and I get absolute file paths in the html as above.

Here's a bash script that replicates the problem for me:

```sh
#!/bin/bash
git clone https://github.com/goldingn/zoon.git
cd zoon
Rscript -e "getwd()"
# Rscript -e "pkgdown::build_site()"
Rscript -e "library(pkgdown); build_site()"
sed '112q;d' docs/reference/articles/Building_a_module.html
cd ..
rm -rf zoon
```

I get the following output (truncated):
```
Cloning into 'zoon'...
...
[1] "/Users/nick/Dropbox/temp/build/zoon"
...
Initialising site -----------
...
<p><img src="/Users/nick/Dropbox/Github/zoon/vignettes/building_occ6-1.png" ...
```

**Comment by hadley** [comment]
Ok, just wanted to check that you weren't calling `build_site("absolute/path")`. I'll look into what's going wrong.

**Comment by goldingn** [comment]
great, thanks!

**Comment by jayhesselberth** [comment]
I think this has to do with the use of `output_dir` in the call to render, which has the undesired side-effect of putting in absolute paths to images.

https://github.com/hadley/pkgdown/blob/180ea3b9513e3d185c65338c8027198c254be17f/R/build-articles.R#L68

See discussion in https://github.com/rstudio/rmarkdown/issues/587

It is easy enough to render the HTML in the vignette directory and then move it to `docs/articles` via `file.rename()` as suggested in that issue:

```r
    path <- rmarkdown::render(
      file.path(pkg$path, "vignettes", file_in),
      output_format = format$format,
      output_file = basename(file_out),
      quiet = TRUE,
      envir = new.env(parent = globalenv())
    )
    tweak_rmarkdown_html(path, depth = vig_depth + depth, index = pkg$topics)
    
    vignette_html <- file.path(pkg$path, "vignettes", file_out)
    article_html <- file.path(pkg$path, path, file_out)
    file.rename(vignette_html, article_html)
```

But if there are PNGs generated during the render, they need to be moved from `vignettes` to `docs/articles` as well. I'm not sure how to learn what their names are after the render for moving, and globbing all PNGs in the `vignettes` directory is inelegant (but effective, and maybe safe?).

**Comment by hadley** [comment]
I think it'd probably be easier to copy the vignette to the target dir, build there, and then delete.

Maybe even better to copy the complete contents of the vignette dir, build, and then delete the Rmds.

**Comment by goldingn** [comment]
👌 works like a charm, thanks both!
