### ISSUE TITLE
autolink functions from @seealso and @family tags?

### ISSUE THREAD

**Issue by jayhesselberth** [hadley/pkgdown#173]
It would be nice if functions referred to by `@family` and `@seealso` tags were auto linked in the HTML reference pages; this would enable easier navigation between related functions in the docs.

**Comment by hadley** [comment]
They are linked family. You have to link yourself in seealso.

If you're using devtools, note that the preview only renders a single file so links don't show.

**Comment by jayhesselberth** [comment]
My `@family` functions are correctly syntax highlighted, but they are not linked to their respective HTML pages. Is this the expected behavior?

I would expect functions in "Other single-set-ops:" in the "See also" section below to be linked, but they're not:

http://jayhesselberth.github.io/valr/reference/bed_flank.html

**Comment by hadley** [comment]
Ooops, sorry, I was pre-coffee and got confused about which repo we were on!

**Comment by hadley** [comment]
Working now :)
