### ISSUE TITLE
Link topics to an edit page on GitHub

### ISSUE THREAD

**Issue by hadley** [hadley/pkgdown#181]
If the project uses github, it would be nice if each document had a link back to the source, so it was easy for readers to contribute pull requests that fix typos etc.

**Comment by jefferis** [comment]
Ha! I had exactly the same thought! This would be a super feature.

**Comment by hadley** [comment]
This is basically a variation on #234, because you'll want to link to the roxygen sources, not the generated Rd files. That means the primary challenge is figuring out the srcref from the usage.
