### ISSUE TITLE
parsing of help cross refs to other packages fails

### ISSUE THREAD

**Issue by jefferis** [hadley/pkgdown#197]
According to [R-exts](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Cross_002dreferences) 

```
\link[=terms.object]{terms}
```

should refer to the S3 "terms" class (in package stats). The relevant help topic is `terms.object` and the Rdocumentation url should be http://rdocumentation.org/packages/stats/topics/terms.object.

However this currently fails for at least two reasons, one trivial, the other more complicated
1. the trivial one see: https://github.com/hadley/pkgdown/commit/e356925a074411d71ba20c9ca518ceab0143e6a4#commitcomment-19581267
2. the complex one: `as_html.tag_link` currently assumes that if a link does not look like `\link[bar]{foo}` or `\link[pkg:bar]{foo}` then `foo` must be a topic in the current package. This assumption is not correct. In fact R-exts rather frowns on this form:

> There are two other forms of optional argument specified as \link[pkg]{foo} and \link[pkg:bar]{foo} to link to the package pkg, to files foo.html and bar.html respectively. These are rarely needed, perhaps to refer to not-yet-installed packages (but there the HTML help system will resolve the link at run time) or in the normally undesirable event that more than one package offers help on a topic83 (in which case the present package has precedence so this is only needed to refer to other packages)

For example if you take a look at the logic here: https://github.com/hadley/pkgdown/blob/master/R/rd-html.R#L106-L123 you'll see that `\link[=terms.object]{terms}` will always end up calling `link_local` whereas in fact what one needs to do is first look to see if the topic exists in the current package and then if it doesn't look for it in other packages. This will require quite a bit of mucking around with `as_html.tag_link`.

**Comment by hadley** [comment]
I don't think we need to worry about looking it up in other packages, we can just look for it in the current package, and not link if not found.

**Comment by jefferis** [comment]
OK. But just to be clear on the implications:
1. sensibly or otherwise R-exts recommends using \link{rnorm} **not** \link[stats]{rnorm} when referring to topics in recommended packages (see quote below)
2. it is not possible to specify the package at the same time as specifying a topic!=label. Therefore references of the form `link[=terms.object]{terms}` which are typical for S3/S4 classes, will only ever work with `rd2html` when the topic is in the current package.

> The only reason to use these forms for base and recommended packages is to force a reference to a package that might be further down the search path. Because they have been frequently misused, the HTML help system looks for topic foo in package pkg if it does not find file foo.html.

**Comment by hadley** [comment]
Yes, that's fine. It's still better than the current totally broken behaviour.

**Comment by jefferis** [comment]
OK I will wrap the trivial fix into https://github.com/hadley/pkgdown/pull/194 and leave this issue for topics outside the current package that will remain broken. To recap, the only link form  to topics outside the current package that `pkgdown` will handle look like `\link[package]{topic}`.

**Comment by hadley** [comment]
This seems to be fixed
