### ISSUE TITLE
Co-existing development vs. stable version of documentation?

### ISSUE THREAD

**Issue by krlmlr** [hadley/pkgdown#202]
Perhaps in `dev/` subdirectory?

**Comment by hadley** [comment]
Could you expand on this a bit? My model is that you'll only work on the website just prior to package release, or you'll use some more sophisticated set up where you're building the docs on travis and putting in a separate branch.

**Comment by krlmlr** [comment]
This is for building dev documentation regularly, perhaps on Travis. It might be useful to also keep the stable version so that it is not overwritten by the dev documentation.

**Comment by hadley** [comment]
Why not just set `path` in `build_reference()`?

**Comment by krlmlr** [comment]
Could do that, but I'd also like to have a link to switch between stable and dev docs. What's the easiest way to implement such a link?

**Comment by hadley** [comment]
A custom navbar?

**Comment by hadley** [comment]
My current model is that if you want extensive customisation, you'll need to write your own version of `build_site()`. Let me know if I've missed any functions that need to be exported to achieve that.  (I should write a vignette about customisation, but that's a long ways off)
