### ISSUE TITLE
Building vignettes - xml errors

### ISSUE THREAD

**Issue by eliotmcintire** [hadley/pkgdown#203]
In our [SpaDES](http://github.com/PredictiveEcology/SpaDES) package, we have 3 vignettes. They knit fine to html when we run them manually, travis and other, but not with pkgdown. The errors are quite cryptic and I am unable to identify their cause. In terms of reproducible example, one of the vignettes is [here](https://raw.githubusercontent.com/PredictiveEcology/SpaDES/master/vignettes/i-introduction.Rmd), the other is [here](https://raw.githubusercontent.com/PredictiveEcology/SpaDES/master/vignettes/i-plotting.Rmd)

Any thoughts?

```
pkgdown::build_articles()
#Building articles ---------------------------------------------------------------------------------------------
#Building article 'iii-plotting.html'
#DEM read from C:/Eliot/GitHub/SpaDES/inst/maps/DEM.tif using raster(inMemory=FALSE)
#forestCover read from C:/Eliot/GitHub/SpaDES/inst/maps/forestCover.tif using #raster(inMemory=FALSE)
#habitatQuality read from C:/Eliot/GitHub/SpaDES/inst/maps/habitatQuality.tif using #raster(inMemory=FALSE)
#Error in eval(substitute(expr), envir, enclos) : 
#  Unescaped '<' not allowed in attributes values [38]


pkgdown::build_articles()
#Building articles ---------------------------------------------------------------------------------------------
#Building article 'i-introduction.html'
#Error in UseMethod("xml_attr<-") : 
 # no applicable method for 'xml_attr<-' applied to an object of class "xml_missing"
```

**Comment by hadley** [comment]
It's mostly like because of the munging that pkgdown does to the vignettes.  A `traceback()` would help.

**Comment by bhaskarvk** [comment]
I have similar errors building NEWS.md

```markdown
# leaflet.esri 0.1.0

* Initial Release with Esri basemap layers support.
```

```r
pkgdown::build_news()
Building news -------------------------------------------------------------------
Error in UseMethod("xml_attr<-") : 
  no applicable method for 'xml_attr<-' applied to an object of class "xml_missing"

> traceback()
9: FUN(X[[i]], ...)
8: lapply(x, `xml_attr<-`, attr = attr, ns = ns, value = value)
7: `xml_attr<-.xml_nodeset`(`*tmp*`, "class", value = "hasAnchor")
6: xml2::`xml_attr<-`(`*tmp*`, "class", value = "hasAnchor")
5: tweak_anchors(xml, only_contents = FALSE)
4: markdown(file.path(pkg$path, "NEWS.md"), "--section-divs", depth = depth, 
       index = pkg$topics)
3: data_news(pkg, depth = depth)
2: build_news_single(pkg, path, depth)
1: pkgdown::build_news()
```

**Comment by bhaskarvk** [comment]
Any updates on this? I'm seeing this error consistently for NEW.md files.

**Comment by bhaskarvk** [comment]
Ah ha! 
I needed to introduce a second level heading. That fixed it.

```md
# leaflet.esri 0.1.0

## Changes

* Initial Release with Esri basemap layers support.
```

**Comment by hadley** [comment]
@bhaskarvk & @eliotmcintire can you please try again now?

**Comment by eliotmcintire** [comment]
Thank you! That fixed it for me.

**Comment by bhaskarvk** [comment]
My error was already solved by adding proper levels.
FWIW, I think `devtools::use_news_md()`, should generate a news file that's compatible with `pkgdown`. Currently the file generated is not (or at least wasn't compatible the last time I checked)
