### ISSUE TITLE
Links to index.html

### ISSUE THREAD

**Issue by krlmlr** [hadley/pkgdown#205]
...perhaps could just strip the file name. That file usually will be shown by default when visiting a URL that points to a directory. (It depends on the web server configuration, so an opt-out might become necessary, too.)

**Comment by hadley** [comment]
It could, but that breaks local preview (without running server). That's a nice feature IMO.

**Comment by krlmlr** [comment]
`build_site(..., local = FALSE)` (or `local = TRUE`)? Also, `servr::httd("docs")` works for me (but requires trailing slashes for directories).

**Comment by hadley** [comment]
Using explicit file names makes it easier to serve in more situations. It's slightly inelegant but not enough that I want to change the behaviour (although I'd review a PR if you really wanted it)
