### ISSUE TITLE
`template:` or `templates:`?

### ISSUE THREAD

**Issue by jayhesselberth** [hadley/pkgdown#206]
The `build_site` docs indicate that `template:` can be specified in the YAML (to change the bootswatch theme), but only `templates:` has an effect (`templates:` is used in the pkgdown [`_pkgdown.yml`](https://github.com/hadley/pkgdown/blob/master/_pkgdown.yml#L1)).

**Comment by yiluheihei** [comment]
I also came across the same trouble, and fixed this problem ,see in #208
