### ISSUE TITLE
url-encoded UTF-8 URLs don't work?

### ISSUE THREAD

**Issue by AdrianHordyk** [hadley/pkgdown#210]
Link to CRAN download doesn't work due to UTF-8 encoding. 
I notice the github links on http://hadley.github.io/pkgdown/ return 404 as well. 
Is this just a Chrome issue?

**Comment by AdrianHordyk** [comment]
Commenting out [this line](https://github.com/hadley/pkgdown/blob/master/R/build-home.R#L228) seems to do the trick. But I assume it is there for a reason!

**Comment by hadley** [comment]
Ooops sorry. It's not utf-8 encoding - I'm insert zero width spaces so that the link gets better line breaks.  Accidentally did both the text and link.
