### ISSUE TITLE
Support multiple URLs in DESCRIPTION

### ISSUE THREAD

**Issue by jranke** [hadley/pkgdown#214]
This is encouraged in http://127.0.0.1:11683/doc/manual/R-exts.html#The-DESCRIPTION-file and works for the CRAN package pages.

**Comment by hadley** [comment]
What do you mean by support?

**Comment by jranke** [comment]
Currently, if you specify more 
than one URL speparated by ", 
", they are treated as one URL 
by pkgdown and this one URL 
therefore does not work.

**Comment by hadley** [comment]
You can add those links using the `home$links` field in the yaml

**Comment by jranke** [comment]
Nice, that make sense!
