### ISSUE TITLE
\item{\dots} is displayed as "&#8230;", not as dots.

### ISSUE THREAD

**Issue by jranke** [hadley/pkgdown#215]
See for example http://jranke.github.io/mkin/reference/print.mkinmod.html

**Comment by yiluheihei** [comment]
IMO, it was duo to [this line](https://github.com/hadley/pkgdown/blob/master/R/render.r#L106), which means this bug is inherited from package whisker

**Comment by jranke** [comment]
Ah, thanks for the hint to whisker.render. Actually this is expected behaviour 
https://github.com/edwindj/whisker#note
and it is easily fixed for the special case I am referring to by using {{{ }}} instead of {{ }}.
