### ISSUE TITLE
Building README.Rmd may fail due to HTML preview

### ISSUE THREAD

**Issue by krlmlr** [hadley/pkgdown#217]
By default, `rmarkdown::github_document()` includes `html_preview = TRUE`, which in turn runs `pandoc` a second time with the `--self-contained` option. This second run fails if *any* download fails (see [example](https://travis-ci.org/krlmlr/bindr/jobs/174595458#L830) of failing to download codecov badge).

For now, I'm [turning off](https://github.com/krlmlr/bindr/commit/950c527d3a9fd3660ce61d9a6ddb6650f05f969f) HTML preview in my `README.Rmd`. Can pkgdown always render with `html_preview = FALSE`?

**Comment by hadley** [comment]
I'm not entirely sure how to fix this — I don't really want to override your default output settings because you might have deliberately customised them.

**Comment by krlmlr** [comment]
I'd argue you never want `html_preview = TRUE` when running pkgdown.

**Comment by hadley** [comment]
I agree, but how to do selectively override just that one argument to `github_markdown()`?

**Comment by krlmlr** [comment]
I think `rmarkdown::render(output_options = list(html_preview = FALSE))` should do the job.

**Comment by hadley** [comment]
That was easy, thanks!
