### ISSUE TITLE
No link to pdf vignettes in "articles" tab

### ISSUE THREAD

**Issue by edzer** [hadley/pkgdown#220]
As an example, see [here](https://edzer.github.io/units/articles/index.html): the [pdf vignette](https://edzer.github.io/units/articles/measurement_units_in_R.pdf) is there, but the index.html has no link to it.

In other words: the "All vignettes" list does not contain all vignettes.

**Comment by hadley** [comment]
Yeah, I've assumed html vignettes. I'm unlikely to fix this myself (since I'm moving to exclusively html vignettes), but I'd be happy to review a PR

**Comment by edzer** [comment]
So am I when I can choose, the exception here comes a vignette that is a manuscript in the pipeline for the R Journal, or alternatively the Journal of Statistical Software. It'll take a while before these two journals also accept html only...

**Comment by yiluheihei** [comment]
@edzer a  manual workaround: embed a pdf to the index.html with html element , or optimize the `build_site` function to check if there is a "pdf vignette" to embed a pdf in the site automatically
