### ISSUE TITLE
problem with auto installation of gh devtools

### ISSUE THREAD

**Issue by restonslacker** [hadley/pkgdown#223]
I had the CRAN version of devtools installed and tried to install pkgdown (`devtools::install_github("hadley\pkgdown")`), but it failed with the following message:
```
"C:/PROGRA~1/R/R-33~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/swenchel/AppData/Local/Temp/Rtmp8ixEN7/devtools122862d91f6/hadley-devtools-2e3c4b6" --library="C:/Users/swenchel/Documents/R/win-library/3.3" --install-tests 

ERROR: dependencies 'pkgbuild', 'pkgload' are not available for package 'devtools'
* removing 'C:/Users/swenchel/Documents/R/win-library/3.3/devtools'
```

this was after a number of dependencies installed correctly.  I then ran `devtools::install_github("hadley\devtools")` which worked as expected and reran `devtools::install_github("hadley\pkgdown")` at which point it installed correctly.

**Comment by hadley** [comment]
This is due to bugs in devtools which should be fixed in the near future
