### ISSUE TITLE
Uncategorized topics?

### ISSUE THREAD

**Issue by krlmlr** [hadley/pkgdown#224]
Currently, if _pkgdown.yml has a `reference` section, all topics that are not included explicitly are skipped, with a warning. @hadley: Should we add these topics to a new "Uncategorized" section instead?

**Comment by hadley** [comment]
That was the previous behaviour, but it wasn't quite in your face enough, and too easy to miss. That's why I switched to warnings.

**Comment by krlmlr** [comment]
Automated builds then should use `options(warn = 2)`. Or would you support a better way?

**Comment by hadley** [comment]
Generally seems like a good principle to run "production" code with `options(warn = 2)`
