### ISSUE TITLE
Bad html in docs/index.html

### ISSUE THREAD

**Issue by jranke** [hadley/pkgdown#228]
I stumbled across these:

`<![endif]-->` in http://github.com/hadley/pkgdown/blob/7c49ac5/docs/index.html#L5

Stray `html` and `body` tags in
http://github.com/hadley/pkgdown/blob/7c49ac5/docs/index.html#L66
and
http://github.com/hadley/pkgdown/blob/7c49ac5/docs/index.html#L70

**Comment by hadley** [comment]
The first issue appears to be fixed by the latest xml2.
