### ISSUE TITLE
Error in setwd(wd) : character argument expected

### ISSUE THREAD

**Issue by xguardi** [hadley/pkgdown#233]
Hi!

When building:
> pkgdown::build_home()

I get the error:

Building home ------------------
Error in setwd(wd) : character argument expected

Any thoughts?
Thanks in advance!

**Comment by yiluheihei** [comment]
Home package building requires one of the following four files in your package root: 

**1) index.Rmd; 2) index.md; 3) README.Rmd; 4) README.md**
