### ISSUE TITLE
top level index.md/html need to be deleted on exit

### ISSUE THREAD

**Issue by jayhesselberth** [hadley/pkgdown#235]
If a index.Rmd file is used, top level index.md and index.html are created but are not deleted on exit, causing a 'non-standard files' NOTE during a package check.

**Comment by yiluheihei** [comment]
you can excluding this files with `.Rbuildignore`file while package building and checking

 e.g. add the following lines in the  .Rbuildignore

```
^index\.Rmd$
^index\.md$
^index\.html$
```
