### ISSUE TITLE
Return sections with item missing

### ISSUE THREAD

**Issue by PascalKieslich** [hadley/pkgdown#237]
Hi,

thanks a lot for the helpful package!

I ran into the following problem: Using `\item{value1}{The first value}` in the return section works fine in the R help but the corresponding sections are missing in the online documentation.

An example: in the following function everything is displayed correctly in the R help, but the information about value1 and value2 is missing online.

```
#' @return This is just an example assuming I would like to provide information on two values:
#' \item{value1}{The first value}
#' \item{value2}{The second value}
```

I think this is related to #54 but this issue was closed (and all related issues as well).

**Comment by dchiu911** [comment]
I'm getting the same issue as well.

My **Value** section only shows

> A list with the following elements

without the list.
