### ISSUE TITLE
Exclude internal help topics by default

### ISSUE THREAD

**Issue by krlmlr** [hadley/pkgdown#238]
https://github.com/hadley/pkgdown/pull/225#issuecomment-264312037

This looks slightly difficult. The current matchers (in topic_matcher()) generate functions that accept a character argument (which doesn't have internality information) and apply to both help topics and articles. We could refactor this to generate functions that accept lists of objects, but I'd rather do this in a separate PR.

**Comment by hadley** [comment]
Probably the easiest way would be to make the matcher functions take two arguments `topics` and `internal`. Then you'd have (e.g.)

```R
starts_with = function(x, drop_internal = TRUE) {
  function(topics, internal) { 
    keep <- grepl(paste0("^", x), topics)
    if (drop_internal) {
     keep <- keep & !internal
   }
   keep
}
```

You could simplify the logical condition to `grepl(paste0("^", x), topics) & (!drop_internal | !internal)` (I think - but the fact that I'm not sure suggests that this is probably too clever)

**Comment by krlmlr** [comment]
How would this apply to articles (see [the call to topic_matcher() in has_vignette()](https://github.com/hadley/pkgdown/blob/1e4f6bb6cbd905dd0572a1cccb5df6202fd3d205/R/build-articles.R#L228))?

**Comment by hadley** [comment]
It would get a vector saying all vignettes are not-internal?
