### ISSUE TITLE
Error in strsplit(help, "/") : non-character argument

### ISSUE THREAD

**Issue by jemus42** [hadley/pkgdown#239]
My first run of `pkgdown::build_site()` worked fine, but all subsequent attempts failed with this error.

```
Building home -----------------------------------------------
Updating README.md
Building article 'index.html'
Building function reference ----------------------------------
Loading tRakt
Error in strsplit(help, "/") : non-character argument
```

It doesn't seem to be code from my package (`tRakt`) and I can't seem to figure out what I might have done wrong to trigger it.

**Comment by mhahsler** [comment]
I get the same error. I think it has something to do with references to other packages. For example, this seems to create the error  `\code{\link[stats]{dist}}`.

**Comment by hadley** [comment]
I couldn't recreate the exact error you're seeing, so I've had to guess a bit at the underlying problem. If this doesn't fix it, please file a new issue with a minimal package that illustrates the problem.
