### ISSUE TITLE
load_all() creates a union class issue

### ISSUE THREAD

**Issue by amatsuo** [hadley/pkgdown#240]
When I tried to run `pkgdown::build_site()` for `quanteda` package it generates following errors
```
Error in .walkClassGraph(ClassDef, "contains", where, attr(ext, "conflicts")) : 
  the 'superClass' list for class “character”, includes an undefined class “textORtokens”
 Show Traceback
 
 Rerun with Debug
 Error in setClassUnion("charNULL", c("character", "NULL")) (from dictionaries.R#2) : 
  unable to create union class:  could not set members "character" 
```
After some googling, I found 
https://github.com/hadley/devtools/issues/657

I suspected `dev_tools::load_all()` (L90-93 in build-reference.R) is causing the problem. 
I commented out these lines and re-installed the package
https://github.com/amatsuo/pkgdown
Then rerun the function did not cause the issue (and output seems just fine). 

Is there a better way to deal with this problem? You will be able to reproduce the problem by cloning 
https://github.com/kbenoit/quanteda
and build, then `build_site()`.

The session_info is:
```
Session info -------------------------------------------------------------
 setting  value                       
 version  R version 3.3.1 (2016-06-21)
 system   x86_64, darwin13.4.0        
 ui       RStudio (1.0.44)            
 language (EN)                        
 collate  en_GB.UTF-8                 
 tz       Europe/London               
 date     2016-12-05     
```

**Comment by hadley** [comment]
Please file a minimal reproducible example on https://github.com/r-pkgs/pkgload
