### ISSUE TITLE
Wide knitr::kable 

### ISSUE THREAD

**Issue by maelle** [hadley/pkgdown#245]
Awesome package, thanks! In the website for https://github.com/ropensci/riem, http://ropensci.github.io/riem/index.html in the README I use `knitr::kable()` and it is wider than the rest of the README text.

![table](https://cloud.githubusercontent.com/assets/8360597/21053079/17bdc5fa-be28-11e6-9f59-fa0082b3d105.png)

Not sure if this is a suggestion for improving pkgdown or if this mean I should use something else to show the table in the README. :-)

**Comment by hadley** [comment]
Yeah, I'm not sure what I could do here?

Do you have any ideas @yihui?

**Comment by yihui** [comment]
You may add the following CSS rules:

```css
table {
    display: block;
    overflow: auto;
}
```

**Comment by maelle** [comment]
@yihui thanks, e.g. file:///C:/Users/Maelle/Documents/ropenaq/docs/index.html looks much better now 😺  should this be a default?

**Comment by yihui** [comment]
I'm able to scroll:

![image](https://cloud.githubusercontent.com/assets/163582/23973466/51105440-09a4-11e7-9e70-e5df05578a09.png)

**Comment by hadley** [comment]
Works for me too; re-opening since it seems useful to enable in general (and maybe for images too?)

**Comment by maelle** [comment]
So weird I couldn't scroll but well now I can, thank you :-) and awesome if it gets enabled in general!
