### ISSUE TITLE
Rendering of [desc](url) markdown-type links.

### ISSUE THREAD

**Issue by privefl** [hadley/pkgdown#246]
For example 
`#' [RStudio](https://www.rstudio.com/)`
give a working link with `RStudio` as link text in the R help.
Yet, in the site built with `pkgdown::build_site()`, the link text is `https://www.rstudio.com/`.

I am using the latest GitHub versions of `hadley/pkgdown` and `klutometis/roxygen`.

**Comment by hadley** [comment]
Please provide a reproducible example

**Comment by privefl** [comment]
Sorry, I thought that giving the example `#' [RStudio](https://www.rstudio.com/)` was sufficient.

Illustration on one of my package:
- line in doc: https://github.com/privefl/primefactr/blob/master/R/primes.R#L3
- line in man: https://github.com/privefl/primefactr/blob/master/man/IsPrime.Rd#L17
- corresponding output on website: https://privefl.github.io/primefactr/reference/IsPrime.html

Is this sufficient?
Thanks

**Comment by PascalKieslich** [comment]
I think the example above could look as follows when using .Rd formatting tags:
`#'  \href{https://www.rstudio.com/}{RStudio}`

The desired result would be this: [RStudio](https://www.rstudio.com/), i.e., the text RStudio linking to the website. This also works fine in the R documentation.

However, when building the online documentaton using `pkgdown::build_site()`, the text (RStudio) is ignored and instead the link is displayed directly as the text as well, i.e., like this: [https://www.rstudio.com/](https://www.rstudio.com/)
