### ISSUE TITLE
Distinguish @name field in list of functions

### ISSUE THREAD

**Issue by surmann** [hadley/pkgdown#247]
`pkgdown` lists the functions and the value in the `@name` field in the reference list. This confuses the reader, because he or she thinks there is one additional function available, which is only the name.

Please emphasis the name, e.g. in brackets behind the title or add an option to suppress it.

**Comment by jranke** [comment]
This problem only appears if the title is the same (or very similar) to the name of the function, right?

**Comment by surmann** [comment]
I don't think so. But, perhaps I am wrong. Here is an example:
`#' @title Inner, Left, Right, Outer, Semi and Anti Join for Data Tables`
`#' @name JoinTables`
This file contains many functions like `ijoin`, `ljoin`, etc.

The reference html paragraph looks like this:
### Inner, Left, Right, Outer, Semi and Anti Join for Data
- JoinTables
- ijoin
- ljoin
- ...

Is that what you think of?

**Comment by jranke** [comment]
Ah, I see. When using roxygen, I usually do not use the @name tag. From the roxygen docs:

@name topicname Override the default topic name, which is taken by default from the object
that is assigned to in the code immediately following the roxygen block. This tag is useful
when documenting datasets, and other non-function elements.

Why do you want to use it here? You can group functions to be documented in the same topic using @rdname.

**Comment by jranke** [comment]
OK, I see now. You can of course still link to any of the function names described in this file. But in your use case your suggestions made above make sense.

Could be that @hadley is not too enthusiastic about supporting further use cases? No wonder, given the number of packages he writes and maintains (thanks, thanks, and again thanks Hadley!)

**Comment by surmann** [comment]
For me it was important to communicate my suggestion understandably. It is up to @hadley whether he thinks it worth implementing.

**Comment by hadley** [comment]
My solution for this will be #256. There's no easy way to figure out if the name is important or not.
