### ISSUE TITLE
Select topics based on other Rd fields

### ISSUE THREAD

**Issue by surmann** [hadley/pkgdown#248]
It is possible to summarise functions of similar contents via `_pgkdown.yml` in different sections. This file has to be fixed for every change and every new function.
Does it make sense to use e.g. the `@section` or `@family` field in the R file for this functionality? It would be much more easily and dynamically to handle.

**Comment by jranke** [comment]
What do you mean by "summarise"? If you are thinking of collecting similar functions, this can already be done. Also, if you name functions in a similar way, you can use the starts_with() or ends_() with syntax to avoid typing the name of each new function.

http://hadley.github.io/pkgdown/reference/build_reference.html

**Comment by surmann** [comment]
You are right, I'm thinking of sections in the references as you see [here](https://dirkschumacher.github.io/ompr/reference/index.html).
These functions are very helpful, but you still have to use them in `_pkgdown.yml`. If the sections are build with respect to a reasonable field, this effort is not necessary any more.

**Comment by jranke** [comment]
I see two options: using @rdname to document objects together (maybe also using @inheritParams), or using explicit sections in the yaml file to group the functions/datasets.

**Comment by surmann** [comment]
Equal @rdname tag to combine the content of different .R files into one .Rd will confuse the reader. We would like to have single .Rd files.

Would you see an advantage to generate the sections via @section tag compared to explicit sections in the yml file?

**Comment by hadley** [comment]
So I think what you're asking for is an another way to select functions like `starts_with()` or `ends_with()` but based on some other field in the Rd?

**Comment by surmann** [comment]
This is an alternative possibility. I thought of a reference grouping directly via roxygen tags.
What is easier to implement and more generic?

**Comment by hadley** [comment]
Pkgdown only looks at Rd files

**Comment by surmann** [comment]
In this case your proposal would be a good solution.
