### ISSUE TITLE
build_home(): Error in file(con, "r") : cannot open the connection

### ISSUE THREAD

**Issue by pat-s** [hadley/pkgdown#263]
##  Debugging:

Caused by `render_rmd()`:

```R
render_rmd(pkg, input, "index.html", depth = depth, 
      data = data, toc = FALSE, strip_header = TRUE)
```

> Quitting from lines 18-20 (README.Rmd) 
> Error in file(con, "r") : cannot open the connection

Problematic lines in `README.Rmd` (first R code chunk in README):

```R
description <- readLines("DESCRIPTION")
version <- gsub(" ", "", gsub("Version:", "", 
                grep("Version:", description, value = TRUE)))
```

**Comment by hadley** [comment]
I don't understand the problem

**Comment by pat-s** [comment]
When calling `build_home()`, I get the above mentioned error. 

It is caused by 

```r
version <- gsub(" ", "", gsub("Version:", "", 
                grep("Version:", description, value = TRUE)))
```

I did not find a solution and just used a direct assignment `version <- "0.1"` instead of trying to `gsub()` it from the DESCRIPTION file. The error is only thrown by `build_home()` and not when normally knitting `README.Rmd`.

**Comment by hadley** [comment]
Closing since you seem to have a solution.
