### ISSUE TITLE
Suggestion for articles documentation ("ignored" vignettes)

### ISSUE THREAD

**Issue by ijlyttle** [hadley/pkgdown#267]
Reference: https://github.com/hadley/pkgdown/blob/master/vignettes/pkgdown.Rmd#articles

From a package-building perspective, it may not be sufficient to add `foo.Rmd` to `.Rbuildignore`. If you created the vignette using `devtools::use_vignette()`, it seems you also need to remove the `vignette:` material from the yml header in `foo.Rmd`.

I "discovered" this the hard way; it took some head-scratching to realize.

Happy to make a PR to add my lesson-learned.

**Comment by xhdong-umd** [comment]
I had similar experience that `build_articles` didn't respect `.Rbuildignore`. I added the `.Rmd` in `vignettes` folder with `devtools::use_build_ignore`, but `build_articles` will still try to build these rmd files.

**Comment by hadley** [comment]
@ijlyttle can you please be a bit more precise about the problem? What function is trying to build the vignette that has been `.Rbuildignore`'d

@xhdong-umd I think you're describing the opposite problem. pkgdown deliberately does not respect `.Rbuildignore` for vignettes.

**Comment by dracodoc** [comment]
@hadley I probably misunderstood the documentation.  I wanted to avoid vignettes building because it will take a long time, so I add the folder because of this

> In the extreme case where you want to produce only articles but not vignettes, you can add the complete vignettes/ directory to .Rbuildignore.

Actually I can just skip vignettes building by calling several build function individually instead of using `build_site`, so it's not a problem.

**Comment by ijlyttle** [comment]
I have made a reproducible example: https://github.com/ijlyttle/vignettebuild

When I run `devtools::build()`,  it is not sufficient that the file appear in `.Rbuildignore` for nothing to appear in the `inst/doc` directory of the `tar.gz` file.

For nothing to appear in `inst/doc`, I also have to remove the `vignette:` from the yaml header that `devtools::use_vignette()` puts there.

I don't know if this is the intended behavior or not, so I thought I would raise the more-modest (documentation) issue here. If this is not the intended behavior of `devtools::build()`, it's no problem for me to file the issue there.

-----

```
> session_info()
Session info -----------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, darwin13.4.0        
 ui       RStudio (1.1.57)            
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Chicago             
 date     2017-03-12                  

Packages ---------------------------------------------------------------------------------------------------
 package       * version    date       source        
 devtools      * 1.12.0     2016-06-24 CRAN (R 3.3.0)
 digest          0.6.12     2017-01-27 cran (@0.6.12)
 git2r           0.18.0     2017-01-01 CRAN (R 3.3.2)
 memoise         1.0.0      2016-01-29 CRAN (R 3.3.0)
 rstudioapi      0.6        2016-06-27 CRAN (R 3.3.0)
 utilrSE       * 0.1.99     2017-02-04 local         
 vignettebuild * 0.0.0.9000 2017-03-13 local         
 whisker         0.3-2      2013-04-28 CRAN (R 3.3.0)
 withr           1.0.2      2016-06-20 CRAN (R 3.3.0)
```

**Comment by hadley** [comment]
This is interesting. Seems to be a bug in R itself, but I think we can work around it here.

Can you confirm that the vignette doesn't get built if it doesn't contain the vignette metadata? And it doesn't generate an R CMD check error?  That's what I'm seeing, and if that's the case we can just tell people to not include the vignette metadata.

**Comment by ijlyttle** [comment]
I can confirm that the vignette does not get built if it doesn't contain the vignette metadata.

When I run `R CMD check --as-cran vignettebuild_0.0.9.tar.gz`, I do not get an error. However, I do get a NOTE on the vignette *with* the vignette metadata that is also in `.Rbuildignore`:

```
* checking for old-style vignette sources ... NOTE
Vignette sources only in ‘inst/doc’:
  ‘i_get_built.Rmd’
A ‘vignettes’ directory is required as from R 3.1.0
and these will not be indexed nor checked
```

To summarize, I am seeing what you are seeing - but I do get a NOTE (which, now that I am reminded, is what had originally alerted me that there was something amiss).

**Comment by hadley** [comment]
I don't see that note with this .Rbuildignore:

```
^.*\.Rproj$
^\.Rproj\.user$
^vignettes/i_get_built\.Rmd$
```

**Comment by ijlyttle** [comment]
Curiouser and curiouser...

Just to be perfectly particular, I have removed some company-specific things from my `.Rprofile`, to be sure that they are not interfering. 

I ran again, this time using `devtools::check()`, and I get the same result:

```
R CMD check results
0 errors | 0 warnings | 1 note 
checking for old-style vignette sources ... NOTE
Vignette sources only in ‘inst/doc’:
  ‘i_get_built.Rmd’
A ‘vignettes’ directory is required as from R 3.1.0
and these will not be indexed nor checked
```

I will try the same thing later today on a Windows machine.

Of course, I am open to any suggestions you have on what to test.

-----

```
> session_info()
Session info -----------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, darwin13.4.0        
 ui       RStudio (1.1.57)            
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Chicago             
 date     2017-03-14                  

Packages ---------------------------------------------------------------------------------------------------
 package       * version    date       source                             
 assertthat      0.1        2013-12-06 CRAN (R 3.3.0)                     
 backports       1.0.5      2017-01-18 cran (@1.0.5)                      
 commonmark      1.1        2016-12-13 cran (@1.1)                        
 crayon          1.3.2      2016-06-28 CRAN (R 3.3.0)                     
 desc            1.1.0      2017-01-27 cran (@1.1.0)                      
 devtools      * 1.12.0     2016-06-24 CRAN (R 3.3.0)                     
 digest          0.6.12     2017-01-27 cran (@0.6.12)                     
 magrittr        1.5        2014-11-22 CRAN (R 3.3.0)                     
 memoise         1.0.0      2016-01-29 CRAN (R 3.3.0)                     
 R6              2.2.0      2016-10-05 cran (@2.2.0)                      
 Rcpp            0.12.9     2017-01-14 cran (@0.12.9)                     
 roxygen2        6.0.0.9000 2017-02-05 Github (klutometis/roxygen@e37ebfc)
 rprojroot       1.2        2017-01-16 cran (@1.2)                        
 stringi         1.1.2      2016-10-01 CRAN (R 3.3.0)                     
 stringr         1.2.0      2017-02-18 cran (@1.2.0)                      
 vignettebuild * 0.0.9      <NA>       local                              
 withr           1.0.2      2016-06-20 CRAN (R 3.3.0)                     
 xml2            1.1.1      2017-02-05 Github (hadley/xml2@c84db5e)
```

**Comment by hadley** [comment]
I'm probably missing something on my end. So a PR improving the documentation would be great, thanks.
