### ISSUE TITLE
Manually copy selected files

### ISSUE THREAD

**Issue by renozao** [hadley/pkgdown#268]
Use case: `README.md` file contains a link to an image also used in a vignette, hence stored under `vignettes/` for package check to find it. Something like `[my link](vignettes/images/my_image.png)`.

When rendering the website with `pkgdown` this link is broken, because the `vignettes/images/` directory is now `articles/images/`.
This can be solved by adding a `vignettes/` sub-directory in `docs/` and duplicating the `images/` directory therein. Not ideal.
Things would work flawless if `docs/articles/` was named `docs/vignettes/`. After all, these files are vignettes.

**Comment by nacnudus** [comment]
Similar use case: `README` loads a file from `inst/extdata/`, which isn't duplicated in `docs/`.

**Comment by hadley** [comment]
@renozao I think the solution to your problem is to allow pkgdown to manually copy specified files

@nacnudus your problem has an easier fix - rely on the package being installed and use `system.file()`.

**Comment by renozao** [comment]
That's right. These could be specified in the yaml config file or, more
conveniently, extracted by parsing README.md file for markdown links.

**Comment by hadley** [comment]
@renozao this is now done automatically for all images in `man/figures` and in `vignettes`
