### ISSUE TITLE
build_reference needs run_dont_test option

### ISSUE THREAD

**Issue by chfleming** [hadley/pkgdown#274]
I have many help file examples wrapped in \donttest{} because I like to test them during R CMD check, but CRAN complains about how long this takes. build_reference() appears to be ignoring all of these examples. I tried the argument run_dont_run=TRUE, but it doesn't seem to extend to \donttest{} (and not that it should). I would find a run_dont_test argument to be very useful.

Also, I have Encoding: UTF-8 set in my DESCRIPTION and \encoding{UTF-8} set in relevant help files, but my UTF-8 characters like é are coming up as � as here:
https://ctmm-initiative.github.io/ctmm/reference/periodogram.html
Maybe I missed an option somewhere?

**Comment by hadley** [comment]
I'm not sure there's any point in `\donttest()` any more, given that CRAN runs it anyway.

**Comment by chfleming** [comment]
If you have examples that take a long time to run and wrap them in `\donttest{}` then CRAN will not run them, though they will ask first and maybe there is some flag that they set... at least still as of February 03. Perhaps this is not common.

**Comment by hadley** [comment]
Actually all code in `\donttest{}` is already run.
