### ISSUE TITLE
Titles with HTML tags 

### ISSUE THREAD

**Issue by keurcien** [hadley/pkgdown#279]
Hi,

Thanks for making this package, it is very useful.
I use to center the titles of my Rmarkdown vignettes by adding the HTML tags in the YAML header (based on the suggestion [here](http://stackoverflow.com/questions/19697402/how-to-center-the-title-in-r-markdown), so the header would look like this:

`title: <center>my_vignette_title</center>`
`output: html_document`

This would make the articles/index.html to reference the vignettes with the HTML tags:

`<li><a href="vignette.html">&lt;center&gt;my_vignette_title&lt;/center&gt;</a></li>` 

when one would rather have something like:

`<li><a href="vignette.html">my_vignette_title</a></li>`

So far, I just manually modify the html code after I run build_site() before pushing.
Don't know if it is an expected behaviour, but I thought I would share. though it doesn't bother me at all to do this manually.

Cheers.

Keurcien

**Comment by hadley** [comment]
You'd be better off using a little custom css, rather than adding html in the header.
