### ISSUE TITLE
Respect CRAN recommendations for images

### ISSUE THREAD

**Issue by hadley** [hadley/pkgdown#280]
> If the images are also used for vignettes or Rd files, you can put them
> in the 'vignettes' or 'man/figures' directories.  Otherwise, please put
> them in the top-level 'tools' directory, or a subdirectory of it.

This probably means we should copy all files with common image extensions from those directories.

**Comment by hadley** [comment]
All files in `vignettes` and `man/figures` are now copied; I think this just means we should tweak the location of any relative image links on the homepage.

**Comment by IndrajeetPatil** [comment]
@hadley I created a webpage for my package with `pkgdown` and, as recommended here, all my figures from `man/figures/x.png` are getting copied to `reference/figures/x.png` (https://github.com/IndrajeetPatil/ggstatsplot/tree/master/docs/reference/figures) when I run `pkgdown::build_site()`. But the resulting website still doesn't display any of the images:
https://indrajeetpatil.github.io/ggstatsplot/

What can I change to display the images properly?

**Comment by hadley** [comment]
@IndrajeetPatil please open a new issue, and include links to the source readme and generated `index.html` in github

**Comment by IndrajeetPatil** [comment]
Done! Thanks.
