### ISSUE TITLE
Separate paragraphs are joined if text is indented

### ISSUE THREAD

**Issue by PascalKieslich** [hadley/pkgdown#281]
I updated pkgdown to the current version on GitHub (my last version was from February 10, 2017) and since the update, the following issue occurs:

The code in the documentation looks as follows:
```
#' @references Text1
#'   
#'   Text2
#'   
#'   Text3
```

This is displayed in the R help as:

**References**

Text1

Text2

Text3

However, in the documentation created with pkgdown it is displayed as:

**References**

Text1 Text2 Text3

This seems to have to do with the indentation, because when the code above is changed to:

```
#' @references Text1
#' 
#' Text2
#' 
#' Text3
```

The result both for the R documentation and the documentation created with pkgdown is:

**References**

Text1

Text2

Text3

As far as I know, this issue has not occurred before the update, i.e., in the pkgdown version from February 10.

Best,

Pascal

**Comment by hadley** [comment]
I couldn't reproduce your problem either using code:

```R
flatten_para(rd_text("Text\n\nText\n\nTest\n"))
flatten_para(rd_text("Text\n\n  Text\n\n  Test\n"))

as_data(rd_text("\\section{X}{Text\n\n  Text\n\n  Test\n}", fragment = FALSE)[[1]])
```

Or directly inserting your roxygen tags.

Are you sure you have the latest dev version of pkgdown?

**Comment by PascalKieslich** [comment]
I have checked the example again. The problem still occurs for me, but

**Comment by PascalKieslich** [comment]
I have checked the example again. The problem still occurs for me, but my problem solution description was not accurate. What seems to cause the joining of the paragraphs is the formatting of the empty lines between the paragraphs. Specificially, if the empty lines in between contain the same amount of spaces at the end like the spaces at the beginning of the indented text blocks, no separate paragraphs will be created.

Getting back to my example above: This will be (incorrectly) displayed as a single paragraph:
```
#' @references Text1
#'   
#'   Text2
#'   
#'   Text3
```

This will be correctly displayed as three parahraphs:
```
#' @references Text1
#'
#'   Text2
#'
#'   Text3
```

**Comment by hadley** [comment]
Can you please create a reproducible example using the template above?

**Comment by PascalKieslich** [comment]
Do you mean embedding the example above in a function? I can do that.

This example will result in a single paragraph in the reference section:
```
#' Add together two numbers.
#' 
#' Function adds together two numbers.
#' 
#' @param x A number.
#' @param y A number.
#' @return The sum of \code{x} and \code{y}.
#' @references Text1
#'   
#'   Text2
#'   
#'   Text3
add <- function(x, y) {
  x + y
}
```

This will result in three paragraphs:
```
#' Add together two numbers.
#' 
#' Function adds together two numbers.
#' 
#' @param x A number.
#' @param y A number.
#' @return The sum of \code{x} and \code{y}.
#' @references Text1
#'
#'   Text2
#'
#'   Text3
add <- function(x, y) {
  x + y
}
```

**Comment by PascalKieslich** [comment]
Regarding the code you provided. I think your code should reproduce my problem if you modify it as follows:
```
flatten_para(rd_text("Text\n\nText\n\nTest\n"))
flatten_para(rd_text("Text\n  \n  Text\n  \n  Test\n"))

as_data(rd_text("\\section{X}{Text\n  \n  Text\n  \n  Test\n}", fragment = FALSE)[[1]])
```
But this is just a guess, as I haven't used these functions before.

**Comment by hadley** [comment]
Please do use those functions to create a minimal reprex for me

**Comment by PascalKieslich** [comment]
Using the modified code I suggested I can reproduce the problem.

The code is (as above):
```
flatten_para(rd_text("Text\n\nText\n\nTest\n"))
flatten_para(rd_text("Text\n  \n  Text\n  \n  Test\n"))

as_data(rd_text("\\section{X}{Text\n  \n  Text\n  \n  Test\n}", fragment = FALSE)[[1]])
```

The output is:
```
> pkgdown:::flatten_para(pkgdown:::rd_text("Text\n\nText\n\nTest\n"))
[1] "<p>Text</p>\n<p>Text</p>\n<p>Test</p>"
> pkgdown:::flatten_para(pkgdown:::rd_text("Text\n  \n  Text\n  \n  Test\n"))
[1] "<p>Text\n  \n  Text\n  \n  Test</p>"
> pkgdown:::as_data(pkgdown:::rd_text("\\section{X}{Text\n  \n  Text\n  \n  Test\n}", fragment = FALSE)[[1]])
$title
[1] "X"

$contents
[1] "<p>Text"  "Text"     "Test</p>"
```

As discussed above, I think that what causes the joining of the paragraphs is the formatting of the empty lines between the paragraphs. Specificially, if the empty lines in between contain the same amount of spaces at the end like the spaces at the beginning of the indented text blocks, no separate paragraphs will be created.
