### ISSUE TITLE
Unable to render <img> tag in main title

### ISSUE THREAD

**Issue by Enchufa2** [hadley/pkgdown#283]
The first line of one of my `README.Rmd` contains a logo:

```
# <img src="someimage" alt=""> some text
```

which I expect to be rendered as

```
<h1 class="hasAnchor">
  <a href="#plot" class="anchor"> </a>
  <img src="someimage" alt=""> some text
</h1>
```

but, instead, I'm getting (note the `<html>` tags)

```
<h1 class="hasAnchor">
  <html><a href="#plot" class="anchor"> </a></html>
  <img src="someimage" alt=""> some text
</h1>
```

which triggers the following error:

```
Writing '/path/to/index.html'
Error in doc_parse_raw(x, encoding = encoding, base_url = base_url, as_html = as_html,  : 
  Opening and ending tag mismatch: img line 3 and h1 [76]
```

Traceback:

```r
> traceback()
6: xml2::xml_replace(header, xml2::read_xml(page_header)) at build-home.R#115
5: tweak_homepage_html(html, strip_header = strip_header) at build-home.R#125
4: update_homepage_html(out_path(path, "index.html"), isTRUE(pkg$meta$home$strip_header)) at build-home.R#85
3: build_home(pkg, path = path) at build.r#155
2: build_site(preview = TRUE) at build.r#180
1: (function () 
   {
       devtools::document()
       build_site(preview = TRUE)
   })()
```

**Comment by hadley** [comment]
Can you please try installing the latest version of pkgdown and xml2?

**Comment by Enchufa2** [comment]
I'm already running the latest version of pkgdown and latest (GitHub) version of xml2.

**Comment by hadley** [comment]
If this doesn't resolve your problem, can you please create a reprex, following the structure of the new test?

**Comment by Enchufa2** [comment]
This solves the problem, thanks.

The problem with the space that is rendered before the image (#285) remains. Do you want me to open a new issue to keep track of that?

**Comment by hadley** [comment]
I don't understand the problem, so yes please.
