### ISSUE TITLE
 unused argument (html_preview = FALSE)

### ISSUE THREAD

**Issue by jentjr** [hadley/pkgdown#286]
I am getting the error below when running ```pkgdown::build_site()```
```
Error in (function (variant = "markdown_strict", preserve_yaml = FALSE,  : 
  unused argument (html_preview = FALSE)
```

**Comment by hadley** [comment]
What the's yaml metadata at the top of your readme?

**Comment by jentjr** [comment]
```
---
output:
  md_document:
    variant: markdown_github
---
```

Thanks for looking into this. I commented out line 64 ```              output_options = list(html_preview = FALSE),``` in build-home.r and was able to get it to  work, but wasn't sure what the intent was and didn't want to submit a pull request.

**Comment by hadley** [comment]
Basically we're assuming that you're using `github_document()` which is now a better way to generate md for github. I think you can just switch to that; pkgdown will work and you won't lose anything.

**Comment by jimhester** [comment]
I ran into this as well, it might be nice to print a more informative error message for this case, it wasn't at all clear what the issue was from the traceback.

**Comment by florianm** [comment]
I just ran into the same issue and the solution was not immediately evident from the discussion above.

To save others frustration:

The README.Rmd created from `devtools::use_readme_rmd()` has the header
```
---
output:
  md_document:
    variant: markdown_github
---
```

To get `pkgdown::build_home()` (and ultimately `pkgdown::build_site()`) to work, change this header to 
```
---
output:
  github_document
---
```
