### ISSUE TITLE
Extra space before <img> in main title

### ISSUE THREAD

**Issue by Enchufa2** [hadley/pkgdown#291]
After #283 and related to #285. Let me explain this with a couple of screenshots. Currently,

```
# <img src="someimage" alt=""> some text
```

produces the following:

```
<h1 class="hasAnchor">
  <a href="#plot" class="anchor"> </a>
  <img src="someimage" alt=""> some text
</h1>
```

The problem is that this is rendered as follows (note the selected whitespace between the anchor and the image):

![sshot-1](https://cloud.githubusercontent.com/assets/4542928/24116443/18f4535c-0da7-11e7-9aa2-d0e40826ad12.png)

Instead, I'd expect this:

![sshot-2](https://cloud.githubusercontent.com/assets/4542928/24116499/4b221ce2-0da7-11e7-92f3-23e4eb2cf312.png)

This can be achieved by removing the newline between the anchor and the image:

```
<h1 class="hasAnchor">
  <a href="#plot" class="anchor"> </a><img src="someimage" alt=""> some text
</h1>
```

**Comment by hadley** [comment]
Are you sure that's not because you're writing

```
# <img src="someimage" alt=""> some text
```

instead of 

```
#<img src="someimage" alt=""> some text
```

**Comment by Enchufa2** [comment]
Yes, I am. That's not the problem. The output (HTML and rendering) is the same, so this is a product of the newline.

**Comment by hadley** [comment]
Oh got it. I think this is a minimal reprex:

```R
html <- xml2::read_html('<div class="contents">
  <div id="x">
    <h1>abc</h1>
  </div>
</div>')

tweak_anchors(html)
html
```

**Comment by hadley** [comment]
@jimhester any idea why I'm getting a new line after the `<h1>` in the commit above? I think `xml_add_sibling()` is inserting it

**Comment by Enchufa2** [comment]
86f7e33 solves the issue with the `<img>` tag, thanks! But you are right: the new line after `<h1>` shouldn't be there either.

**Comment by jimhester** [comment]
`as.character.xml_node()` has a default option of `'format'`, which pretty prints the output. You can turn it off by passing `options = ""`.

``` r
library(magrittr)
html <- xml2::read_html('<div class="contents">
  <div id="x">
    <h1>abc</h1>
  </div>
</div>')

pkgdown:::tweak_anchors(html)
html %>% xml2::xml_find_first(".//h1") %>% as.character(options = "") %>% cat()
#> <h1 class="hasAnchor"><html><body><a href="#x" class="anchor"> </a></body></html>abc</h1>
```

**Comment by hadley** [comment]
Oh duh, thanks
