### ISSUE TITLE
Parse and display citations

### ISSUE THREAD

**Issue by edzer** [hadley/pkgdown#295]
It would be nice if `pkgdown` would also process `inst/CITATION`, e.g. as a fourth item next to <pkg> Reference Articles Citation

**Comment by jayhesselberth** [comment]
Not sure it deserves its own page. Could be in the sidebar on the main page e.g. Links, License, Developers, Citation.

**Comment by edzer** [comment]
Either way!

**Comment by jayhesselberth** [comment]
Actually probably the best place is on the current `authors.html` page, where there is fair bit of open space. Not sure an entire citation would fit in the sidebar.

**Comment by yiluheihei** [comment]
Citations can be displayed in the sidebar, probably  configuration options can be supported in `config.yaml` to order the elements of sidebar for users (e.g. Links, License, Developers, Citation).
Or, it can be added to the last section of home page.

**Comment by jayhesselberth** [comment]
Saw this: https://github.com/ropensci/unconf17/issues/46.

I was thinking all along that a DOI / zenodo badge would be useful, but it's not a required part of the CITATION file. Not sure what a sensible default would be.
