### ISSUE TITLE
pkgdown generated ampersands (&amp;) sometimes malformed

### ISSUE THREAD

**Issue by davebraze** [hadley/pkgdown#297]
Using pkgdown installed fresh this morning:

Ampersands in the generated `docs/reference/index.html` file are malformed. They are generated as `&amp;amp;`. See <https://github.com/davebraze/FDBwordsets/blob/master/docs/reference/index.html#L100>, for example.

Ampersands in other files within `docs/reference` seem ok.

**Comment by yiluheihei** [comment]
#298

**Comment by davebraze** [comment]
Thank you!
