### ISSUE TITLE
Bioconductor packages 

### ISSUE THREAD

**Issue by yiluheihei** [hadley/pkgdown#305]
Bioconductor is an open source and open development project for bioinformatics analysis which based primarily on the R statistical programming language.  It  now has 1296 software R packages, and an active user community.  Thus, it would be nice to if there is a bioconductor links  in the home page sidebar.

**Comment by hadley** [comment]
What should they link to?

**Comment by yiluheihei** [comment]
like cran links. Download from Bioconductor at http://www.bioconductor.org/packages/release/bioc/html/packagename.html

**Comment by hadley** [comment]
Want to do a PR? You can follow the same template as `data_link_cran()`. I don't know how you'd implement `on_bioc()`, but presumably it's fairly simple.

**Comment by LiNk-NY** [comment]
@hadley @yiluheihei 
You can get a link to the package via:
https://bioconductor.org/packages/<pkgname>
That will redirect to either release or devel which ever is available first in that order.

**Comment by LiNk-NY** [comment]
@hadley 
You sort of need `BiocInstaller::biocinstallRepos` to get a reliable link over time. 
I can send a PR with what I have.

**Comment by yiluheihei** [comment]
@LiNk-NY Function `BiocInstaller::all_group()` will return the names of all Bioconductor software packages

**Comment by LiNk-NY** [comment]
Hi @yiluheihei, 
Yes, that is just a wrapper to the functions being used. I will update the PR in a minute. 
Thanks, 
Marcel

**Comment by LiNk-NY** [comment]
Okay so **PR** #318 should take care of this now. 
Best, 
Marcel
