### ISSUE TITLE
Documentation for the templates

### ISSUE THREAD

**Issue by bhaskarvk** [hadley/pkgdown#306]
Where can I find the documentation for crating custom templates ?
I need to know how to use the various variables provided by the template engine as well as looping or any other constructs it provides, to be able to create custom templates.

**Comment by hadley** [comment]
You'll have to read the source. I'm not sure these templates will stay as is, so I'm not documenting yet

**Comment by coatless** [comment]
From rOpenSci's Slack:

> Templating is done with [`mustache`](http://mustache.github.io/) through the _R_ library [`whisker`](https://github.com/edwindj/whisker), which `pkgdown` imports

Courtesy of Neal Richardson and Zhian Kamvar for the future google searcher.
