### ISSUE TITLE
Improve mobile experience

### ISSUE THREAD

**Issue by jimhester** [hadley/pkgdown#312]
On mobile the navbar takes up a large portion of the screen with mostly white space, covers part of the content at the top and remains fixed as you scroll. The navbar also seems to have a lot of extra padding on mobile sizes, which makes the problem worse.

I think an easy fix for this would be to make the navbar absolutely positioned at the top with mobile view sizes.

## Vertical
<img width="412" alt="screenshot 2017-04-05 08 08 06" src="https://cloud.githubusercontent.com/assets/205275/24704923/a7cf806a-19d7-11e7-91d4-1b184d165f05.png">

## Horizontal
<img width="670" alt="screenshot 2017-04-05 08 08 21" src="https://cloud.githubusercontent.com/assets/205275/24704924/a7d21956-19d7-11e7-9ebc-4a43f4d36e53.png">

**Comment by jimhester** [comment]
This seems to work fine for the default pkgdown css (from http://stackoverflow.com/a/11974519/2055486). The issue is really more of a problem with the tidyverse css however, I will open a corresponding issue there.

```diff
diff --git a/inst/assets/pkgdown.css b/inst/assets/pkgdown.css
index fd7b0ba..cde7682 100644
--- a/inst/assets/pkgdown.css
+++ b/inst/assets/pkgdown.css
@@ -63,6 +63,17 @@ a.anchor {
   margin-top: -60px;
 }

+@media (max-width: 979px) {
+  .navbar-fixed-top {
+    position: absolute;
+    margin: 0;
+  }
+}
+
+.navbar-absolute + div {
+    margin-top: 68px;
+}
+
 /* Sidebar --------------------------*/

 #sidebar {
```

**Comment by hadley** [comment]
Should be a lot better now
