### ISSUE TITLE
build_articles() needs to ignore rsconnect

### ISSUE THREAD

**Issue by jennybc** [hadley/pkgdown#315]
If you've ever previewed and published a vignette with rpubs, you will have an `rsconnect` subdirectory in `vignettes/`. `build_articles()` should ignore that.

I think that means `copy_dir()` needs to have some inclusion/exclusion criteria. I almost made a PR then wasn't sure how you would want this fixed. If you want to offer some guidance, I will make the attempt.

https://github.com/hadley/pkgdown/blob/86f7e334fe2f06fddc8a742ee5562866a2cab1bc/R/util.r#L158-L171

**Comment by hadley** [comment]
One possible hack would be to simply ignore anything in `.gitignore`. I don't know if there's anything off the shelf that would make implementing that easy, though.

**Comment by hadley** [comment]
Ooops, just saw you offered to do a PR for this. It was moderately painful to implement — another reason we need a good cross platform file manipulation package.
