### ISSUE TITLE
support for custom css and js

### ISSUE THREAD

**Issue by jjallaire** [hadley/pkgdown#317]
It would be nice to allow for custom CSS and Javascript to be injected into the site (or even a chunk of custom HTML before and after the body).

**Comment by hadley** [comment]
How would you want to specify that? 

The easiest way to implement this would be to add three new template parameters: `head`, `header,` footer`. You could specify those in the yaml, allowing you to inject arbitrary text in the 3 places where you're mostly likely to be interested. The text would be specified in the yaml, so it wouldn't be suitable for larger amounts of content.

There's an existing way to add arbitrary additional assets so you could just link to those:

```R
template:
- assets: path/to/more/assets/that/are/copied
```

**Comment by jjallaire** [comment]
I think most people will think to specify this using R Markdown YAML (e.g.
css and includes options). You could make that work by just creating a
custom format for rendering pkgdown (then people could include their css
and includes options under the pkgdown::article format rather than the
rmarkdown::html_vignette format).

**Comment by saurfang** [comment]
Just echo my use case here: for a lighter touch skinning, it would be useful to include additional CSS/js automatically. Right now, if I don't want to change the header template, I need to overwrite the `pkgdown.css` (make a copy first) and add my modification inside. (or copy the `header.html` and modify the template.) Either approach seems more complicated than it needs to be.

**Comment by jjallaire** [comment]
That's what I do (post process the built site by appending to pkgdown.css).

@hadley If there was a way to fully use R Markdown to render pages that
would solve this issue and the aforementioned htmlwidget/htmleDependencies
issue. I realize the current system supports using arbitrary page
generation environments (Jekyll, etc.) but perhaps you could have a mode
that uses R Markdown more fully that gets all these features for free
(rather than having to re-invent them for pkgdown).

**Comment by hadley** [comment]
After chatting with @jjallaire I suggest that pkgdown recognises the special `pkgdown/extra.css` and `pkgdown/extra.js`. If these are found, they'll be copied to `doc/` and automatically linked to with the appropriate `<script>`/ `<style>` tags.

We'll also recognise `pkgdown/_pkgdown.yml` so that if you do use this special directory, you can use it for everything.
