### ISSUE TITLE
autolink for article("name")

### ISSUE THREAD

**Issue by jennybc** [hadley/pkgdown#320]
It would be nice if `article("name")` got auto linked as `vignette("name")`. Or if `vignette("name")` just picked up non-vignette articles too.

https://github.com/hadley/pkgdown/blob/10011cf1ce2927b43b390e8adde5dc8a85021e4f/R/highlight.r#L224

**Comment by hadley** [comment]
`vignette("name")` should pick up non-vignette articles already (in fact I don't think it does anything smart — it just pastes together a url)

But we think about how people might find articles from within an R package

**Comment by jennybc** [comment]
> `vignette("name")` should pick up non-vignette articles already

In my hands, this is not quite true.

> (in fact I don't think it does anything smart — it just pastes together a url)

But this comment inspired me to prepend the `articles/` subdirectory and then it *does* work.

Example: readxl has a vignette `sheet-geometry.Rmd` and an article `articles/readxl-workflows.Rmd`.

Does auto link: `vignette("sheet-geometry")`
Does not auto link: `vignette("readxl-workflows")`
Does auto link: `vignette("articles/readxl-workflows")`

Maybe this is what you meant along.

**Comment by hadley** [comment]
Can you provide a reprex? This is the code that autolinks `vignette()`:

```R
link_vignette <- function(expr, text, depth) {
  if (length(expr) != 2) {
    return(NA_character_)
  }

  href <- paste0(up_path(depth), "articles/", as.character(expr[[2]]), ".html")
  paste0("<a href='", href, "'>", text, "</a>")
}
```

**Comment by jennybc** [comment]
I think I answered by own question here:

> Example: readxl has a vignette `sheet-geometry.Rmd` and an article `articles/readxl-workflows.Rmd`.
> 
> Does auto link: `vignette("sheet-geometry")`
> Does not auto link: `vignette("readxl-workflows")`
> Does auto link: `vignette("articles/readxl-workflows")`
>
> Maybe this is what you meant all along.

You just need to refer to articles with the `articles/` directory prefixed.

**Comment by hadley** [comment]
You definitely shouldn't need `articles/` because the auto-linker adds that for you.

**Comment by jennybc** [comment]
Yes, all the vignettes are below `articles/`. But the "articles" are below `articles/articles/`.

https://github.com/tidyverse/readxl/tree/master/docs/articles

That's what I meant by `article("name")` vs `vignette("name")` for prepending `articles/articles/` vs. `articles/`. Otherwise, I guess you actually need to go looking for such a file to get the path right.

**Comment by hadley** [comment]
Ooooooh, got it.
