### ISSUE TITLE
options() leakage

### ISSUE THREAD

**Issue by jennybc** [hadley/pkgdown#321]
The readxl pkgdown site prints a lot of tibbles. I find that options such as `options(tibble.print_min = 4, tibble.print_max = 4)` "leak" from my current R session into `pkgdown::build_site()` and possibly from file to file within the site (?).

Reproduce by grabbing readxl source. Build the site. Commit or at least stage. Now execute with your favourite integer:

```r
options(tibble.print_min = 7, tibble.print_max = 7)
```

and build the site again.

**Comment by hadley** [comment]
This is in the examples, presumably, which are run in the current session.  They should probably all be run in a new session. I could run each in its own session, but that would be stricter than R CMD check and would add an overhead of ~250ms for each example.

**Comment by hadley** [comment]
You might also want to use the RStudio add-in which runs in a clean session.
