### ISSUE TITLE
Indicate active navigation category

### ISSUE THREAD

**Issue by hadley** [hadley/pkgdown#326]
Needs `class="active"` so that navbar indicates current section within the site.  

@jjallaire

**Comment by hadley** [comment]
This is going to be fiddlier than I thought. Needs at least these two pieces:

```R
local_path <- function(path, depth = 0) {
  if (file.exists(path) && !is_dir(path)) {
    depth <- depth + 1
  }

  pieces <- strsplit(path, "/")[[1]]
  n <- length(pieces)

  paste(pieces[(n - depth):n], collapse = "/")
}

common_path_length <- function(x, y) {
  x <- strsplit(x, "/")[[1]]
  y <- strsplit(y, "/")[[1]]

  n <- min(length(x), length(y))
  for (i in seq_len(n)) {
    if (x[[i]] != y[[i]]) {
      return(i - 1L)
    }
  }

  i
}
```

Although might be possible to do something simpler with a carefully considered regexp.

**Comment by jjallaire** [comment]
In the Keras site I'm finding that the "Home" and "Articles" tabs are always highlighted active:
<img width="649" alt="screen shot 2017-06-20 at 5 47 36 pm" src="https://user-images.githubusercontent.com/104391/27357565-ad35dd34-55e0-11e7-849c-7d13e573cc7d.png">

Perhaps due to a custom navbar structure? https://github.com/rstudio/keras/blob/master/_pkgdown.yml

**Comment by hadley** [comment]
Does it work when published? I don't think my js handles local paths that well.

**Comment by hadley** [comment]
Nope, scratch that. There are two problems with your custom navbar + my javascript:

* Home always gets highlighted because `/index.html` is a prefix of every path. I can special case that

* Articles probably gets highlighted because it has a different structure to what I was expecting (I forgot about nested navbars). When do you think it should get highlighted? When any of its children match the current path?

**Comment by jjallaire** [comment]
The way I've seen nested navbars handled is to do a jquery looking for a
matching href, then just add the "active" class to all of it's parents.
Here's the catch-all script for this I use in R Markdown websites:
https://github.com/rstudio/rmarkdown/blob/d5d22b92a1341b248927cca5423ee3d7a65c30f1/inst/rmd/h/default.html#L209-L222

**Comment by hadley** [comment]
The problem for the menu is that that while the href is "#", the pathname is expanded to the path of the current document. I'm not sure how to work around that yet.

**Comment by hadley** [comment]
Oh `value.getAttribute("href")`
