### ISSUE TITLE
prevent generation of Rd lines > 90 characters wide

### ISSUE THREAD

**Issue by jjallaire** [hadley/pkgdown#330]
A long S3 class name currently results in this warning from R CMD check:

```
* checking Rd line widths ... NOTE
Rd file 'fit.ImageDataGenerator.Rd':
  \usage lines wider than 90 characters:
     ## S3 method for class 'tensorflow.contrib.keras.python.keras.preprocessing.image.ImageDataGenerator'

Rd file 'fit.Tokenizer.Rd':
  \usage lines wider than 90 characters:
     ## S3 method for class 'tensorflow.contrib.keras.python.keras.preprocessing.text.Tokenizer'
```

**Comment by hadley** [comment]
I think this is a roxygen2 issue. But is there any way to manually break the lines that doesn't trigger a warning?

**Comment by jjallaire** [comment]
I've tried various manual edits to the Rd file to prevent the warnings but they result in other errors :-\

**Comment by hadley** [comment]
I think you're going to have to ask CRAN, and I think they are going to tell you not to use such long class names 😬

**Comment by jjallaire** [comment]
Hopefully by the time Keras goes into TF 1.2 the class name will be reduced to:

tensorflow.keras.preprocessing.image.ImageDataGenerator

and we'll dodge this issue for now!

**Comment by jjallaire** [comment]
FYI I managed to figure out a way to make the class name smaller which I
agree is the only legit solution here.

**Comment by skeydan** [comment]
Nice I stumbled on this googling for that error message ;-))
I have the same thing with a function argument that looks like 

```
step_size_setter_fn = tfp$mcmc$simple_step_size_adaptation$`_hmc_like_step_size_setter_fn`,
```

The only thing I could think of was introducing a hack like this

```
tfp_mcmc_sssa <- function() tfp$mcmc$simple_step_size_adaptation
step_size_setter_fn = tfp_mcmc_sssa()$`_hmc_like_step_size_setter_fn`,
```

as I have no control over the class names and/or function names...

**Comment by hadley** [comment]
@skeydan can't you just break it up into multiple lines?

```R
step_size_setter_fn = tfp$
  mcmc$
  simple_step_size_adaptation$
  `_hmc_like_step_size_setter_fn`
```

**Comment by skeydan** [comment]
Thanks! But with that I still get

```
N  checking Rd line widths ...
   Rd file 'mcmc_simple_step_size_adaptation.Rd':
     \usage lines wider than 90 characters:
          step_size_setter_fn = tfp$mcmc$simple_step_size_adaptation$`_hmc_like_step_size_setter_fn`,
          step_size_getter_fn = tfp$mcmc$simple_step_size_adaptation$`_hmc_like_step_size_getter_fn`,
          log_accept_prob_getter_fn = tfp$mcmc$simple_step_size_adaptation$`_hmc_like_log_accept_prob_getter_fn`,
   
   These lines will be truncated in the PDF manual.
```

It's just a note though, not a warning ... (somehow I overlooked that before & thought it was the cause of travis failing...)

**Comment by hadley** [comment]
Oh it's in the usage? You'll need some other approach then. Maybe set the default to NULL?

**Comment by skeydan** [comment]
We normally try to indicate the actual defaults from Python so users can see them in the help...

**Comment by hadley** [comment]
I think you'll have to sacrifice that so that you can get the package on CRAN.

**Comment by skeydan** [comment]
would you say the above hack (https://github.com/r-lib/pkgdown/issues/330#issuecomment-481808788) is too ugly? Technically it works...

**Comment by hadley** [comment]
I think you'd have to document and export it for it to be substantially better than using NULL, and that's a lot more work.

**Comment by skeydan** [comment]
Got it :-)
Thx!
