### ISSUE TITLE
Allow other extensions for the NEWS file

### ISSUE THREAD

**Issue by nuno-agostinho** [hadley/pkgdown#331]
According to the [Bioconductor rules regarding Bioconductor packages](http://master.bioconductor.org/packages/devel/bioc/vignettes/BiocCheck/inst/doc/BiocCheck.html#news-checks), the NEWS file should be either named `NEWS` or `NEWS.Rd`. As pkgdown only parses `NEWS.md` files, Bioconductor packages are not able to leverage this feature.

**Comment by hadley** [comment]
I'm not going to implement this myself, but I'd review a PR.
