### ISSUE TITLE
Rd tables mangled on conversion to html

### ISSUE THREAD

**Issue by goldingn** [hadley/pkgdown#348]
`as_html.tag_tabular()` inserts too many newlines when converting Rd `\tabular` sections to html. The following code should return a one-row two-column table, but instead returns a two-row, one column table (note the extra `</tr><tr>` in the middle):

```r
table <- '\\tabular{ll}{a \\tab b \\cr}'
pkgdown:::rd2html(table)
```
```
[1] "<table><tr><td>a </td>" "</tr><tr><td> b </td>"  "</tr></table>"  
```

The expected output is:
```
[1] "<table><tr><td>a </td>" "<td> b </td>"           "</tr></table>"   
```

The culprit is [the first line of `as_html.tag_tabular()`](https://github.com/hadley/pkgdown/blob/master/R/rd-html.R#L236), which grabs the alignment characters. For some reason it drops the first one (the `[-1]`), so the alignment characters are converted from `ll` (two columns) to `l` (one column). The number of columns is determined form these, so everything is shoved into a single column.

Here's a test that catches this:

```r
table2 <- '\\tabular{ll}{a \\tab b \\cr}'
out <- rd2html(table2)
expect_equal(out, c("<table><tr><td>a </td>", "<td> b </td>", "</tr></table>"))
```

**Comment by goldingn** [comment]
I'd be happy to submit a PR removing the `[-1]` and adding the test.

**Comment by hadley** [comment]
A PR with test would be great!  I'm sure I added the -1 for a reason, so it's likely that I some weird table in one of my packages, and we'll need to adapt to also handle that once I encounter it again.
