### ISSUE TITLE
specify graphics device

### ISSUE THREAD

**Issue by bowerth** [hadley/pkgdown#349]
I am currently trying to figure out how a parameter from `_pkgdown.yml` can be passed to the `build_markdown_format` function in [R/build-articles.R](https://github.com/hadley/pkgdown/blob/9c7fe0b55ec73c883771a347e1dec9d6ea2055c5/R/build-articles.R#L124)
It is possible to obtain e.g. SVG in the output by hard-wiring the output format but maybe someone has a more elegant solution

```
  list(
    path = path,
    format = rmarkdown::html_document(
      toc = toc,
      toc_depth = 2,
      self_contained = FALSE,
      theme = NULL,
      template = path,
      dev = "svg"
    )
```

**Comment by hadley** [comment]
This seems like a good idea, but unfortunately it's not high enough on my priority list that I will implement it myself. However, I'd be happy to review a PR.
