### ISSUE TITLE
Type of regex recognized by matches

### ISSUE THREAD

**Issue by slwu89** [hadley/pkgdown#352]
Thanks for the fantastic utility!

I am wondering what types of regex are supported by `matches` for the .yml config file to generate the reference index. I was trying to use negative lookbehind to selectively filter out functions, see here (want to match to PfSI but not SimBitePfSI): https://regex101.com/r/MZBNtT/1

The error was `invalid regular expression '(?<!SimBite)PfSI', reason 'Invalid regexp'` . Is there any way around this? Could the main functions pass down some parameters to `grepl`?

Thanks.

**Comment by hadley** [comment]
You can do `-starts_with("SimBite")`
