### ISSUE TITLE
Working directory when building index.html

### ISSUE THREAD

**Issue by jennybc** [hadley/pkgdown#355]
The working directory when building index.html is `docs/` but the source file (I've experimented with README.Rmd and index.Rmd) lives at the top-level. This creates the usual problems with file paths to, say, a token file or an embedded image.

I'm working around this by using rprojroot:

```{r, include = FALSE}
token_path <- rprojroot::find_package_root_file("tidyverse-noncaching-token.rds")
googledrive::drive_auth(token_path)
```
or

```{r out.width = '100%', echo = FALSE}
knitr::include_graphics(
  rprojroot::find_package_root_file("bacon.jpg")
)
```

I don't know if this is something to be fixed? Or a gotcha to be documented.

**Comment by jennybc** [comment]
Related: if README.Rmd takes a while to render, it's sort of sad that it gets rendered twice, once to make README.md and immediately again to make index.html. But I realize this won't be generally true with READMEs. I guess this is an incentive to minimize README and put stuff into index.Rmd.

**Comment by hadley** [comment]
Embedded images are complicated because they need to be somewhere that CRAN can also access them, either in the vignettes directory or in `man/figures`.

I'm not sure what to do about other files. rprojroot seems like an OK strategy to deal with them.
