### ISSUE TITLE
installation of hadley/pkgdown leads to uninstall of callr and loop of downloading pkgload, downloading pkgdown

### ISSUE THREAD

**Issue by RMHogervorst** [hadley/pkgdown#359]
Installing pkgdown fails on my windows 10 machine with the message: callr and pkgload are not available for pkgdown. 

the requirement for pkgdown is pkgload and the requirement for pkgload is pkgdown. So the two are calling for eachother. I tried installing the two packages seperately but strangely the package callr from CRAN is then deleted from my system. It is all very weird.

**Comment by hadley** [comment]
pkgload doesn't require pkgdown, so I think the problem must be something different.

**Comment by RMHogervorst** [comment]
You were completely right! I reinstalled rtools and everything worked. (I guess the toolchain was modified when I installed Cygwin recently)
