### ISSUE TITLE
Missing links to items in reference index

### ISSUE THREAD

**Issue by jayhesselberth** [hadley/pkgdown#369]
A relatively recent change (perhaps commit 25210217f4de6f96ca05d52d188d4cd4ccc1f050) is preventing display of links to several items in the reference index.

The following is a (mostly) data package. Links to all of the tables and a variable are missing from the index using the most recent pkgdown: 

http://jayhesselberth.github.io/nihexporter/reference/index.html

**Comment by hadley** [comment]
This should've been fixed in https://github.com/hadley/pkgdown/commit/aebe2288a2056877c788a6fbd759fe5a90f87921. Are you sure you have the absolutely latest version?

**Comment by jayhesselberth** [comment]
Guess not. It's fixed, sorry for the dup
