### ISSUE TITLE
Unsupported person roles?

### ISSUE THREAD

**Issue by Guilz** [hadley/pkgdown#370]
Hello,

Thank you for this great package, it makes presenting documentation so much easier!

I run into a small issue: all people listed in my `Authors@R` field have the correct roles (author, maintainer, contributor) on the website generated by `pkgdown`, except one person who has roles `c("ldr", "led")` in my `DESCRIPTION` file that should become "laboratory director" and "lead" on the website, but instead become "NA, NA".

Does `pkgdown` support all role identifiers from this list?
https://www.loc.gov/marc/relators/relaterm.html

**Comment by hadley** [comment]
No, it currently only supports:

```
role_lookup <- c(
  "aut" = "author",
  "com" = "compiler",
  "fnd" = "funder",
  "ctb" = "contributor",
  "cph" = "copyright&nbsp;holder",
  "cre" = "maintainer",
  "ctr" = "contractor",
  "dtc" = "data&nbsp;contributor",
  "ths" = "thesis&nbsp;advisor",
  "trl" = "translator"
)
```

The other roles aren't generally supported by CRAN, but if you wanted to complete the list, I'd be happy to review a PR.

**Comment by Guilz** [comment]
OK, I will do that sometime this week (I need to figure out which file needs to be edited).

I think lab director is a must have in academia ^^ (it doesn't matter whether CRAN supports it or not for my use case, but I need it on the generated website).

**Comment by Guilz** [comment]
Actually I just figured it out. See #371.
