### ISSUE TITLE
Certain functions don't appear in index

### ISSUE THREAD

**Issue by nhejazi** [hadley/pkgdown#374]
Using the latest version of `pkgdown` (as of 7cde4c8), we are getting an error that might be related to what was reported in #369. Specifically, several functions don't appear in the [index file created under reference](https://benkeser.github.io/survtmle/reference/index.html) -- see topmost category, but each of the functions does have a documentation page generated properly (e.g., [docs page for our `mean_tmle` function](https://benkeser.github.io/survtmle/reference/mean_tmle.html)). I'm not sure why the links are missing in the index file.

Any help would be much appreciated. My apologies if I missed any similar issues (#369 was the only one that looked possibly relevant when I scanned the closed list).

**Comment by jsta** [comment]
I am seeing the same thing with the docs page for our [classifications](https://cont-limno.github.io/LAGOS/reference/classifications.html) man page. A reference html file is generated but it is not linked in the reference index.

**Comment by jayhesselberth** [comment]
I think this is a bug on [this line](https://github.com/hadley/pkgdown/blob/25210217f4de6f96ca05d52d188d4cd4ccc1f050/R/build-reference-index.R#L51)

``` r
aliases = purrr::map2(section_topics$funs, section_topics$name, ~ .x %||% .y),
```
should be
``` r
aliases = purrr::map2(section_topics$alias, section_topics$name, ~ .x %||% .y),
```
Will submit a PR.
