### ISSUE TITLE
Could not find tools necessary to compile a package

### ISSUE THREAD

**Issue by edzer** [hadley/pkgdown#376]
When running `pkgdown::build_stie()` on package https://github.com/r-spatial/sf , I see
```r
> pkgdown::build_site()
Initialising site -------------------------------------------------------------
Copying '/home/edzer/R/x86_64-pc-linux-gnu-library/3.4/pkgdown/assets/jquery.sticky-kit.min.js'
Copying '/home/edzer/R/x86_64-pc-linux-gnu-library/3.4/pkgdown/assets/link.svg'
Copying '/home/edzer/R/x86_64-pc-linux-gnu-library/3.4/pkgdown/assets/pkgdown.css'
Copying '/home/edzer/R/x86_64-pc-linux-gnu-library/3.4/pkgdown/assets/pkgdown.js'
Building home -----------------------------------------------------------------
Writing '/home/edzer/git/sfr/docs/index.html'
Building function reference ---------------------------------------------------
Loading sf
Error: Could not find tools necessary to compile a package
```

<details>

> devtools::session_info()
Session info -------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.1 (2017-06-30)
 system   x86_64, linux-gnu           
 ui       X11                         
 language en_US                       
 collate  en_US.UTF-8                 
 tz       Europe/Berlin               
 date     2017-07-17                  

Packages -----------------------------------------------------------------------
 package    * version    date       source                          
 assertthat   0.2.0      2017-04-11 CRAN (R 3.4.0)                  
 backports    1.0.5      2017-01-18 CRAN (R 3.4.0)                  
 callr        1.0.0      2016-06-18 CRAN (R 3.4.1)                  
 commonmark   1.2        2017-03-01 CRAN (R 3.4.0)                  
 crayon       1.3.2      2016-06-28 CRAN (R 3.4.0)                  
 curl         2.6        2017-04-27 cran (@2.6)                     
 DBI          0.7        2017-06-18 CRAN (R 3.4.0)                  
 desc         1.1.0      2017-01-27 CRAN (R 3.4.0)                  
 devtools     1.12.0     2016-12-05 CRAN (R 3.4.0)                  
 digest       0.6.12     2017-01-27 CRAN (R 3.4.0)                  
 evaluate     0.10.1     2017-06-24 cran (@0.10.1)                  
 git2r        0.18.0     2017-01-01 CRAN (R 3.4.0)                  
 htmltools    0.3.6      2017-04-28 cran (@0.3.6)                   
 httr         1.2.1      2016-07-03 CRAN (R 3.4.0)                  
 knitr        1.16       2017-05-18 cran (@1.16)                    
 magrittr     1.5        2014-11-22 CRAN (R 3.4.0)                  
 MASS         7.3-47     2017-04-21 CRAN (R 3.4.0)                  
 memoise      1.1.0      2017-04-21 CRAN (R 3.4.0)                  
 pkgbuild     0.0.0.9000 2017-04-28 Github (r-pkgs/pkgbuild@8aab60b)
 pkgdown      0.1.0.9000 2017-07-10 Github (hadley/pkgdown@7cde4c8) 
 pkgload      0.0.0.9000 2017-06-12 Github (r-pkgs/pkgload@119cf9a) 
 purrr        0.2.2.9000 2017-07-10 Github (tidyverse/purrr@9cd05b9)
 R6           2.2.2      2017-06-17 cran (@2.2.2)                   
 Rcpp         0.12.11    2017-05-22 CRAN (R 3.4.1)                  
 rlang        0.1.1.9000 2017-07-10 Github (hadley/rlang@ff87439)   
 rmarkdown    1.6        2017-06-15 cran (@1.6)                     
 roxygen2     6.0.1      2017-02-06 CRAN (R 3.4.0)                  
 rprojroot    1.2        2017-01-16 CRAN (R 3.4.0)                  
 stringi      1.1.5      2017-04-07 CRAN (R 3.4.0)                  
 stringr      1.2.0      2017-02-18 CRAN (R 3.4.0)                  
 tibble       1.3.3      2017-05-28 CRAN (R 3.4.0)                  
 udunits2     0.13       2016-11-17 CRAN (R 3.4.0)                  
 units        0.4-6      2017-07-12 local                           
 whisker      0.3-2      2013-04-28 CRAN (R 3.4.0)                  
 withr        1.0.2      2016-06-20 CRAN (R 3.4.0)                  
 xml2         1.1.1      2017-01-24 CRAN (R 3.4.0)                  
 yaml         2.1.14     2016-11-12 CRAN (R 3.4.0)   

</details>

**Comment by hadley** [comment]
What happens if you just do `devtools::load_all()`?

**Comment by edzer** [comment]
Turned out the problem was due to new Rcpp using the _  prefix, and a conflicting `R_registerRoutines` calls; shuffling my build logic resolved it. Thanks and sorry for the noise!
