### ISSUE TITLE
 Could not find tools necessary to compile a package

### ISSUE THREAD

**Issue by jeffwong** [hadley/pkgdown#377]
I am getting an error on 

```
> pkgdown::build_site()
Initialising site -------------------------------------------------------------
Creating 'docs/'
Copying '/root/R/x86_64-pc-linux-gnu-library/3.4/pkgdown/assets/jquery.sticky-kit.min.js'
Copying '/root/R/x86_64-pc-linux-gnu-library/3.4/pkgdown/assets/link.svg'
Copying '/root/R/x86_64-pc-linux-gnu-library/3.4/pkgdown/assets/pkgdown.css'
Copying '/root/R/x86_64-pc-linux-gnu-library/3.4/pkgdown/assets/pkgdown.js'
Building home -----------------------------------------------------------------
Writing '<...>/docs/authors.html'
Writing '<...>/docs/index.html'
Building function reference ---------------------------------------------------
Creating 'docs/reference/'
Loading Mypackage
Error: Could not find tools necessary to compile a package
In addition: Warning message:
Installed Rcpp (0.12.12) different from Rcpp used to build dplyr (0.12.11).
Please reinstall dplyr to avoid random crashes or undefined behavior.
```

Here is the traceback

```
> traceback()
6: stop("Could not find tools necessary to compile a package", call. = FALSE)
5: check_build_tools()
4: pkgbuild::compile_dll(pkg$path, quiet = quiet)
3: pkgload::load_all(pkg$path)
2: build_reference(pkg, lazy = FALSE, examples = examples, run_dont_run = run_dont_run,
       mathjax = mathjax, seed = seed, path = file.path(path, "reference"),
       depth = 1L)
1: pkgdown::build_site()
```

**Comment by hadley** [comment]
What happens if you run `devtools::load_all()`?

(Please don't include session info unless it's explicitly asked for, or you've used `reprex::reprex(..., si = TRUE)` to hide it away. I've deleted it from your issue to avoid cluttering up the discussion)

**Comment by jeffwong** [comment]
Everything passes. I also have some Rcpp code in my package, along with a configure.ac, is that what the error is referring to?

**Comment by jeffwong** [comment]
I'm trying to find this function `pkgbuild::compile_dll` but am unable to locate it. There doesn't seem to be a package called pkgbuild. Same with `pkgload`, it is in the DESCRIPTION under import, but I cannot find it anywhere

**Comment by hadley** [comment]
http://github.com/r-lib/pkgload - you must have installed the dev version of devtools. You might want to switch back to the CRAN version.

**Comment by jeffwong** [comment]
I reinstalled devtools from CRAN and everything works. What a great package!!!

**Comment by ponnet** [comment]
Same error here and the following command:
`devtools::load_all()`
gives

> Error: No root directory found in ... or its parent directories. Root criterion: contains a file `DESCRIPTION`

**Comment by william-vw** [comment]
Same error here .. Not found a solution yet.

**Comment by ChickenWangSY** [comment]
the same error about `Could not find tools necessary to compile a package` when i run `devtools::install_github('cole-trapnell-lab/monocle3')`

then, when I run `devtools::load_all()`, i got 
```
No root directory found in /home/wangshiyou or its parent directories. Root criterion: contains a file `DESCRIPTION`
```

I used anaconda to manage my R , version 3.5.1. could you please give me some advice ?

regards

**Comment by zpingfeng** [comment]
I have similar problem as well

**Comment by XiaoruiZhu** [comment]
After searching a lot solutions, finally I delete .Renviron file in C:\Users\My name\Documents. Then rtools40 works.

**Comment by ethanbass** [comment]
> After searching a lot solutions, finally I delete .Renviron file in C:\Users\My name\Documents. Then rtools40 works.

Does anyone know why this happens?
