### ISSUE TITLE
Documenting executables

### ISSUE THREAD

**Issue by michelk** [hadley/pkgdown#378]
I often have executables  in the packages  `exec` or `inst/bin` folder. Is there already any convention how to document them? 

I thought, I would  generate unix-man pages for each of them. 

Would it be possible to parse unix man-pages, similar to the rd-files, and produce a summary page with a listing of all executables with short summary and then for each a single page?

**Comment by hadley** [comment]
Probably not, because this is such a seldom used part of R.  I'd recommend documenting with regular Rd files.
