### ISSUE TITLE
"Browse source code at" link points to github.io (not the expected github.com)

### ISSUE THREAD

**Issue by JohnMount** [hadley/pkgdown#385]
The "Browse source code at" link points to github.io (not the expected github.com) link.  Example here: http://hadley.github.io/pkgdown/ . The first link in the right links-rail, points to http://hadley.github.io/pkgdown/ , but one would expect it to point to https://github.com/hadley/pkgdown 

![pkgdownlink](https://user-images.githubusercontent.com/4275344/28754508-7b59af7c-74fb-11e7-981c-65b6f354a209.png)

Mostly I want to know if there is a command to control this so I can fix it for my pkgdown sites, I am just using the pkgdown website as a convenient example.  I assume it has something to do with how the URL line is set in the DESCRIPTION file and I could use some help in figuring the rules of that out please.  Part of the problem is the URL field in the DESCRIPTION file is something you want to set to the pkdown site for packages you publish on CRAN (so CRAN links to the nice pkgdown site) however you want the pkdown site itself to link to the github.com site so people can get at the source code easily.

**Comment by hadley** [comment]
It uses the first link in URL that includes github. Maybe I should make the match more stringent and only match on github.com.

**Comment by JohnMount** [comment]
That fixed it for me, thanks.  Also would it make sense for pkgdown to trim whitespace out of URLs?  I wanted to write "URL: https://github.com/WinVector/pkg , http://winvector.github.io/pkg/" with spaces around the comma to make the URL very unambiguous- but that created a broken link.
