### ISSUE TITLE
Home icon links to wrong URL

### ISSUE THREAD

**Issue by wch** [hadley/pkgdown#390]
For example if you go here:
https://rstudio.github.io/shinytest/index.html

The home icon links to https://rstudio.github.io/index.html, which isn't very useful.

**Comment by altaf-ali** [comment]
Another way to reproduce this is if you go to https://hadley.github.io/pkgdown/ and then click on the Home icon, it takes you to Hadley Wickham's github repos at https://hadley.github.io/index.html instead of pkgdown home page.
