### ISSUE TITLE
Standard way of writing links to other functions in package from vignettes

### ISSUE THREAD

**Issue by dmenne** [hadley/pkgdown#420]
Pkgdown does a great job linking function names in R code chunks to the documentation.

But how do I use this feature in RMarkdown? Currently I am using

`[my_fit()](../html/my_fit.html)`

but this does not work in github pages. I tried

`[my_fit](?breathtestcore::my_fit)`

but this does not work correctly.

**Comment by hadley** [comment]
Just do `my_fit()` and pkgdown should link automatically.

**Comment by dmenne** [comment]
For those who want to try: it should be  \`my_fit()\`  within backticks.  @hadley`s backticks were missing in escape.

**Comment by hadley** [comment]
Oh yeah `` `my_fit()` `` - sorry
