### ISSUE TITLE
Package documentation in subdirectory of github.io?

### ISSUE THREAD

**Issue by markdumke** [hadley/pkgdown#431]
How can I create the package documentation as a subdirectory of my existing github.io website? For example I want to have myname.github.io/packageA for the package documentation of one package and myname.github.io/packageB for another package. How do I tell Github to build this websites? Any help appreciated :)

**Comment by jayhesselberth** [comment]
You already have it active for the `reinforcelearn` package.

https://markdumke.github.io/reinforcelearn/

If you want to have a page for a different package, create a new repo for that package and select "master branch /docs folder" for the source under Github Pages in the Settings.

**Comment by markdumke** [comment]
Ah ok, thanks :) I probably should have waited a few more minutes because it didn't show when I looked last.

**Comment by jayhesselberth** [comment]
If you reformat your `README.Rmd`, the badges will be pulled out correctly into the sidebar under "Dev status".

Remove the `include_graphics` chunk,  the `## Reinforcment ...` header, and the `----` spacer. Replace with:

```
# Reinforcement Learning in R <img src="reinforcelearn.png" align="right" height="36"/>
```

Possibly related to #386

**Comment by markdumke** [comment]
Can I use `message = FALSE` for the reference examples?

**Comment by jayhesselberth** [comment]
No, `message = FALSE` is a knitr chunk option, but the examples are not rendered using knitr.

I assume you're concerned about the verbose example output in e.g. https://markdumke.github.io/reinforcelearn/reference/qSigma.html.

You can reduce some of the verbosity by wrapping specific calls with `suppressMessages` in the examples.
